version: "3.7"

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - 12201:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testgoapp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
    - ./config/mysql/mysql.cnf:/etc/mysql/conf.d/
    - ./config/mysql/setup.sql:/docker-entrypoint-initdb.d/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - logging-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    depends_on:
      - elasticsearch
    ports:
      - 12201:12201/udp
    command: bin/logstash-plugin install logstash-input-jdbc
    volumes:
      - ./config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./config/logstash/mysql-connector-java-8.0.15.jar:/opt/mysql-connector-java-8.0.15.jar
    networks:
      - logging-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    depends_on:
      - logstash
    ports:
      - 5601:5601
    networks:
      - logging-network

  httpd:
    image: httpd:latest
    depends_on:
      - logstash
    ports:
      - 81:80
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

networks:
  logging-network:
    driver: bridge