version: "3"

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testgoapp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
    - ./config/mysql/init.sql:/var/lib/mysql
  elasticsearch:
    image: elasticsearch:7.6.0
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
       - "9300:9300"
  logstash:
    image: logstash:7.6.0
    volumes:
      - ./config/logstash/logstash.conf:/config
    depends_on:
      - elasticsearch
    ports:
    - "9600:9600"
  kibana:
    image: kibana:7.6.0
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL="http://es:9600"
    ports:
      - "5601:5601"
  app:
    build:
      context: ./goApp
    volumes:
      - "./Go:/go"
    container_name: go-app
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - db

volumes:
  mysql_data:
  elasticsearch_data: