version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.6.0
    container_name: elastic
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./config/elasticsearch/:/usr/share/elasticsearch/config/
      - es-data:/usr/share/elasticsearch/data
    networks:
      - logging
  logstash:
    image: logstash:7.6.0
    container_name: logstash
    command: logstash -f /config/
    volumes:
      - ./config/logstash:/config
    networks:
      - logging
    depends_on:
      - elasticsearch
      - redis
  kibana:
    image: kibana:7.6.0
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./config/kibana/:/etc/kibana/
    networks:
      - logging
    depends_on:
      - elasticsearch
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - logging
volumes:
  es-data:
    driver: local
  redis-data:
    driver: local

networks:
  logging:
    driver: bridge